language: java
jdk:
  - oraclejdk8
after_success:
  - echo "<settings><servers><server><id>synaptix-snapshots-repository</id><username>\${env.NEXUS_USER}</username><password>\${env.NEXUS_PASSWORD}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml